### ISSUE TITLE
AdvancedEAST文本检测原理简介 | Y.J.Views

### ISSUE THREAD

**Issue by huoyijie** [huoyijie/huoyijie.github.io#1]
https://huoyijie.github.io/2018/08/24/AdvancedEAST%E6%96%87%E6%9C%AC%E6%A3%80%E6%B5%8B%E5%8E%9F%E7%90%86%E7%AE%80%E4%BB%8B/

**Comment by huoyijie** [comment]
# 沙发

* 测试下评论

**Comment by git-manager** [comment]
挺不错的分享，定位优化的很好了，楼主有文字定位了以后的文字识别代码吗，可以的话，拜托楼主发个链接给我，谢谢啦
